volumes:
    sqlite-dbs:

services:
    server:
        image: portfolio-site
        env_file:
            - .env
        build:
            context: ..
            dockerfile: ./docker/Dockerfile
        extra_hosts:
            - "mail-server:172.18.0.1"
        ports:
            - "${SERVER_PORT:-7001}:8080"
        volumes:
            - sqlite-dbs:/home/web-app-user/data
            - "./application-prod.properties:/home/web-app-user/app/application-prod.properties"
        